// ═══════════════════════════════════════════════════════════════
// CONTRACTOR & SERVICE PROVIDER REFERENCE DATA
// Static rate cards for planning — not wired into simulation P&L
// Rates are annual unless noted. "Cross-biz" = shared across entities.
// ═══════════════════════════════════════════════════════════════

// Entity keys used for filtering
export const ENTITIES = {
  V1: 'v1',           // V1 NimbusTech (S-Corp consulting)
  V2: 'v2',           // V2 Agro (farm/land entity)
  NP: 'nonprofit',    // 501(c)(3)
  V3: 'v3',           // Venture 3 (generational wealth vehicle)
  OPS_HUB: 'ops-hub', // Nigeria Ops Hub (V2 subsidiary)
  PERSONAL: 'personal',
};

// Status options
export const STATUS = {
  ACTIVE: 'Active',
  PLANNED: 'Planned',
  FUTURE: 'Future',
};

// ───────────────────────────────────────────────────────────────
// MASTER CONTRACTOR LIST
// Each contractor can serve multiple entities (crossBiz array).
// subpages: which subpage slugs this contractor is most relevant to.
// ───────────────────────────────────────────────────────────────
export const CONTRACTORS = [
  // ═══ NIGERIA OPS HUB — shared back-office ═══
  {
    id: 'ng-accountant',
    role: 'Accountant / Bookkeeper',
    location: '🇳🇬 Nigeria',
    rateRange: '$3K – $6K/yr',
    rateMin: 3000,
    rateMax: 6000,
    type: 'Part-time',
    entity: ENTITIES.OPS_HUB,
    crossBiz: [ENTITIES.V1, ENTITIES.V2, ENTITIES.NP, ENTITIES.V3],
    subpages: ['ops-hub'],
    description: 'Monthly reconciliation, AP/AR, payroll processing for all entities. AI-assisted with QuickBooks/Xero.',
    status: STATUS.PLANNED,
    startAge: 33,
  },
  {
    id: 'ng-tax-compliance',
    role: 'Tax & Compliance Specialist',
    location: '🇳🇬 Nigeria',
    rateRange: '$4K – $7K/yr',
    rateMin: 4000,
    rateMax: 7000,
    type: 'Part-time',
    entity: ENTITIES.OPS_HUB,
    crossBiz: [ENTITIES.V1, ENTITIES.V2, ENTITIES.NP],
    subpages: ['ops-hub'],
    description: 'Quarterly filings, S-Corp distributions, nonprofit compliance, inter-company billing reconciliation.',
    status: STATUS.PLANNED,
    startAge: 33,
  },
  {
    id: 'ng-hr-admin',
    role: 'HR & Admin Coordinator',
    location: '🇳🇬 Nigeria',
    rateRange: '$3K – $5K/yr',
    rateMin: 3000,
    rateMax: 5000,
    type: 'Part-time',
    entity: ENTITIES.OPS_HUB,
    crossBiz: [ENTITIES.V1, ENTITIES.V2, ENTITIES.NP],
    subpages: ['ops-hub'],
    description: 'Onboarding, contractor management, time tracking, benefits admin across all entities.',
    status: STATUS.PLANNED,
    startAge: 33,
  },
  {
    id: 'ng-devops',
    role: 'DevOps / IT Admin',
    location: '🇳🇬 Nigeria',
    rateRange: '$5K – $8K/yr',
    rateMin: 5000,
    rateMax: 8000,
    type: 'Part-time',
    entity: ENTITIES.OPS_HUB,
    crossBiz: [ENTITIES.V1, ENTITIES.V2, ENTITIES.NP],
    subpages: ['ops-hub', 'internal-tools'],
    description: 'Server management, CI/CD, security monitoring, internal tool deployment. AI-assisted.',
    status: STATUS.PLANNED,
    startAge: 34,
  },
  {
    id: 'ng-logistics',
    role: 'Logistics & Procurement',
    location: '🇳🇬 Nigeria',
    rateRange: '$3K – $5K/yr',
    rateMin: 3000,
    rateMax: 5000,
    type: 'Part-time',
    entity: ENTITIES.OPS_HUB,
    crossBiz: [ENTITIES.V2, ENTITIES.NP],
    subpages: ['ops-hub', 'agro-equipment'],
    description: 'Equipment sourcing, supply chain coordination, vendor management for farm and nonprofit ops.',
    status: STATUS.PLANNED,
    startAge: 34,
  },
  {
    id: 'ng-content',
    role: 'Content & Social Media',
    location: '🇳🇬 Nigeria',
    rateRange: '$3K – $5K/yr',
    rateMin: 3000,
    rateMax: 5000,
    type: 'Part-time',
    entity: ENTITIES.OPS_HUB,
    crossBiz: [ENTITIES.V1, ENTITIES.V2, ENTITIES.NP],
    subpages: ['ops-hub', 'content-media'],
    description: 'Social media management, blog posts, video editing, brand content across all entities.',
    status: STATUS.FUTURE,
    startAge: 35,
  },
  {
    id: 'ng-data-analyst',
    role: 'Data / AI / Cyber Analyst',
    location: '🇳🇬 Nigeria',
    rateRange: '$5K – $8K/yr',
    rateMin: 5000,
    rateMax: 8000,
    type: 'Part-time',
    entity: ENTITIES.OPS_HUB,
    crossBiz: [ENTITIES.V1, ENTITIES.V2, ENTITIES.NP],
    subpages: ['ops-hub', 'data-analytics'],
    description: 'Impact metrics, financial dashboards, grant reporting data, portfolio analytics.',
    status: STATUS.FUTURE,
    startAge: 36,
  },

  // ═══ US CPA — officializes filings (minimal) ═══
  {
    id: 'us-cpa',
    role: 'US CPA (Filing & Review)',
    location: '🇺🇸 US',
    rateRange: '$5K – $8K/yr',
    rateMin: 5000,
    rateMax: 8000,
    type: 'Retainer',
    entity: ENTITIES.V1,
    crossBiz: [ENTITIES.V1, ENTITIES.V2, ENTITIES.NP],
    subpages: ['ops-hub'],
    description: 'Reviews and signs off on all filings prepared by ops hub. S-Corp, nonprofit 990, inter-company transfers.',
    status: STATUS.ACTIVE,
    startAge: 31,
  },

  // ═══ V1 NIMBUSTECH — consulting / S-Corp ═══
  {
    id: 'v1-ai-engineer',
    role: 'AI / ML Engineer',
    location: '🇳🇬 Nigeria / Remote',
    rateRange: '$8K – $15K/yr',
    rateMin: 8000,
    rateMax: 15000,
    type: 'Contract',
    entity: ENTITIES.V1,
    crossBiz: [],
    subpages: ['internal-tools'],
    description: 'AI model development, automation pipelines, client project support. Scales with NT revenue.',
    status: STATUS.FUTURE,
    startAge: 34,
  },
  {
    id: 'v1-fullstack-dev',
    role: 'Full-Stack Developer',
    location: '🇳🇬 Nigeria / Remote',
    rateRange: '$6K – $12K/yr',
    rateMin: 6000,
    rateMax: 12000,
    type: 'Contract',
    entity: ENTITIES.V1,
    crossBiz: [],
    subpages: ['internal-tools', 'garden-app'],
    description: 'Web/mobile development for client projects and internal tools. React, Node, Python stack.',
    status: STATUS.FUTURE,
    startAge: 34,
  },
  {
    id: 'v1-project-mgr',
    role: 'Project Manager',
    location: '🇳🇬 Nigeria / Remote',
    rateRange: '$5K – $8K/yr',
    rateMin: 5000,
    rateMax: 8000,
    type: 'Contract',
    entity: ENTITIES.V1,
    crossBiz: [],
    subpages: [],
    description: 'Client communications, sprint planning, deliverable tracking for NT consulting projects.',
    status: STATUS.FUTURE,
    startAge: 35,
  },
  {
    id: 'v1-webull-advisor',
    role: 'Investment Advisor (Webull)',
    location: '🇺🇸 US',
    rateRange: '$2K – $5K/yr',
    rateMin: 2000,
    rateMax: 5000,
    type: 'Retainer',
    entity: ENTITIES.V1,
    crossBiz: [],
    subpages: ['webull-portfolio'],
    description: 'Quarterly portfolio review, rebalancing guidance, tax-loss harvesting strategy for V1 Webull.',
    status: STATUS.PLANNED,
    startAge: 32,
  },

  // ═══ V2 AGRO / HOMESTEAD — farm operations ═══
  {
    id: 'v2-groundskeeper',
    role: 'Groundskeeper',
    location: '🇺🇸 US (On-site)',
    rateRange: '$15K+/yr',
    rateMin: 15000,
    rateMax: 25000,
    type: 'Part-time → scaling',
    entity: ENTITIES.V2,
    crossBiz: [],
    subpages: ['agro-equipment', 'property-management'],
    description: 'Land maintenance, fencing, irrigation, equipment operation. $15K start + 5%/yr raises + perks (meals, housing).',
    status: STATUS.PLANNED,
    startAge: 35,
  },
  {
    id: 'v2-house-manager',
    role: 'House Manager',
    location: '🇺🇸 US (On-site)',
    rateRange: '$15K+/yr',
    rateMin: 15000,
    rateMax: 25000,
    type: 'Part-time → scaling',
    entity: ENTITIES.V2,
    crossBiz: [ENTITIES.PERSONAL],
    subpages: ['property-management'],
    description: 'Household operations, guest management, supplies, scheduling. $15K start + 5%/yr raises.',
    status: STATUS.PLANNED,
    startAge: 38,
  },
  {
    id: 'v2-ops-coordinator',
    role: 'Ops Coordinator',
    location: '🇺🇸 US (On-site)',
    rateRange: '$30K+/yr',
    rateMin: 30000,
    rateMax: 50000,
    type: 'Full-time',
    entity: ENTITIES.V2,
    crossBiz: [ENTITIES.NP, ENTITIES.V1],
    subpages: ['property-management', 'agro-equipment'],
    description: 'First full-time US hire. Oversees all on-site ops, manages other staff, liaison with ops hub. $30K + 5%/yr.',
    status: STATUS.FUTURE,
    startAge: 42,
  },
  {
    id: 'v2-landscape-crew',
    role: 'Landscape Crew Lead',
    location: '🇺🇸 US',
    rateRange: '$5K – $12K/yr',
    rateMin: 5000,
    rateMax: 12000,
    type: 'Seasonal Contract',
    entity: ENTITIES.V2,
    crossBiz: [],
    subpages: ['landscape-consulting'],
    description: 'Seasonal landscaping contracts, tree planting, erosion control, hardscape installation.',
    status: STATUS.FUTURE,
    startAge: 36,
  },
  {
    id: 'v2-vet',
    role: 'Veterinarian (Livestock)',
    location: '🇺🇸 US',
    rateRange: '$2K – $5K/yr',
    rateMin: 2000,
    rateMax: 5000,
    type: 'On-call',
    entity: ENTITIES.V2,
    crossBiz: [],
    subpages: ['agro-equipment'],
    description: 'Livestock health checks, vaccinations, emergency care. On-call retainer.',
    status: STATUS.FUTURE,
    startAge: 35,
  },
  {
    id: 'v2-property-mgr',
    role: 'Property Manager (Rentals)',
    location: '🇺🇸 US',
    rateRange: '$8K – $15K/yr',
    rateMin: 8000,
    rateMax: 15000,
    type: 'Contract',
    entity: ENTITIES.V2,
    crossBiz: [],
    subpages: ['city-rentals', 'property-management'],
    description: 'Manages city rental properties — tenant screening, maintenance coordination, Airbnb listings. 8-10% of gross rent.',
    status: STATUS.PLANNED,
    startAge: 40,
  },
  {
    id: 'v2-garden-app-dev',
    role: 'Mobile App Developer',
    location: '🇳🇬 Nigeria / Remote',
    rateRange: '$5K – $10K/yr',
    rateMin: 5000,
    rateMax: 10000,
    type: 'Contract',
    entity: ENTITIES.V2,
    crossBiz: [ENTITIES.V1],
    subpages: ['garden-app'],
    description: 'Garden/farm app development — React Native, API integrations, sensor data. Shared with V1 dev resources.',
    status: STATUS.FUTURE,
    startAge: 36,
  },

  // ═══ NONPROFIT 501(c)(3) ═══
  {
    id: 'np-mom-ed',
    role: 'Executive Director (Mom)',
    location: '🇺🇸 US',
    rateRange: '$5K → $26K/yr',
    rateMin: 5000,
    rateMax: 26000,
    type: 'Volunteer + Stipend',
    entity: ENTITIES.NP,
    crossBiz: [],
    subpages: ['permaculture', 'community', 'education', 'homestead-support', 'policy', 'data-analytics'],
    description: 'Mom as volunteer ED with growing stipend ($5K start, 20%/yr growth). Oversees all programs, age 35-44.',
    status: STATUS.PLANNED,
    startAge: 35,
    endAge: 44,
  },
  {
    id: 'np-hired-ed',
    role: 'Executive Director (Hired)',
    location: '🇺🇸 US',
    rateRange: '$30K+/yr',
    rateMin: 30000,
    rateMax: 60000,
    type: 'Part-time → Full-time',
    entity: ENTITIES.NP,
    crossBiz: [],
    subpages: ['permaculture', 'community', 'education', 'homestead-support', 'policy', 'data-analytics'],
    description: 'Hired ED replaces mom at age 45. $30K part-time start, 10%/yr raises. Manages programs and grant writing.',
    status: STATUS.FUTURE,
    startAge: 45,
  },
  {
    id: 'np-grant-writer',
    role: 'Grant Writer',
    location: '🇳🇬 Nigeria / Remote',
    rateRange: '$4K – $8K/yr',
    rateMin: 4000,
    rateMax: 8000,
    type: 'Contract',
    entity: ENTITIES.NP,
    crossBiz: [],
    subpages: ['community', 'education', 'policy'],
    description: 'USDA, foundation, and government grant applications. AI-assisted research + ops hub data support.',
    status: STATUS.PLANNED,
    startAge: 35,
  },
  {
    id: 'np-program-coord',
    role: 'Program Coordinator',
    location: '🇺🇸 US / Local',
    rateRange: '$8K – $15K/yr',
    rateMin: 8000,
    rateMax: 15000,
    type: 'Part-time',
    entity: ENTITIES.NP,
    crossBiz: [],
    subpages: ['permaculture', 'community', 'homestead-support'],
    description: 'On-the-ground program execution — workshops, volunteer coordination, community outreach.',
    status: STATUS.FUTURE,
    startAge: 38,
  },
  {
    id: 'np-education-fellow',
    role: 'Education Fellow',
    location: '🇺🇸 US / Local',
    rateRange: '$5K – $10K/yr',
    rateMin: 5000,
    rateMax: 10000,
    type: 'Fellowship',
    entity: ENTITIES.NP,
    crossBiz: [],
    subpages: ['education'],
    description: 'College students / recent grads serving as teaching fellows for ag education and STEM programs.',
    status: STATUS.FUTURE,
    startAge: 38,
  },
  {
    id: 'np-policy-researcher',
    role: 'Policy Researcher',
    location: '🇳🇬 Nigeria / Remote',
    rateRange: '$4K – $7K/yr',
    rateMin: 4000,
    rateMax: 7000,
    type: 'Contract',
    entity: ENTITIES.NP,
    crossBiz: [],
    subpages: ['policy', 'data-analytics'],
    description: 'Agricultural policy research, white papers, advocacy support. Remote research + ops hub coordination.',
    status: STATUS.FUTURE,
    startAge: 40,
  },
  {
    id: 'np-impact-analyst',
    role: 'Impact & Data / AI Analyst',
    location: '🇳🇬 Nigeria / Remote',
    rateRange: '$5K – $8K/yr',
    rateMin: 5000,
    rateMax: 8000,
    type: 'Contract',
    entity: ENTITIES.NP,
    crossBiz: [ENTITIES.OPS_HUB],
    subpages: ['data-analytics'],
    description: 'Program impact measurement, donor reporting dashboards, grant compliance metrics. Shared with ops hub data team.',
    status: STATUS.FUTURE,
    startAge: 37,
  },
  {
    id: 'np-legal',
    role: 'Nonprofit Attorney',
    location: '🇺🇸 US',
    rateRange: '$3K – $6K/yr',
    rateMin: 3000,
    rateMax: 6000,
    type: 'Retainer',
    entity: ENTITIES.NP,
    crossBiz: [],
    subpages: [],
    description: '501(c)(3) compliance, QOZ fund structuring, board governance, liability review.',
    status: STATUS.PLANNED,
    startAge: 33,
  },

  // ═══ VENTURE 3 — Generational Wealth Vehicle ═══
  {
    id: 'v3-trust-attorney',
    role: 'Trust & Estate Attorney',
    location: '🇺🇸 US',
    rateRange: '$5K – $10K/yr',
    rateMin: 5000,
    rateMax: 10000,
    type: 'Retainer',
    entity: ENTITIES.V3,
    crossBiz: [],
    subpages: [],
    description: 'Family trust structuring, generational wealth transfer, dynasty trust setup and maintenance.',
    status: STATUS.FUTURE,
    startAge: 58,
  },

  // ═══ CROSS-BUSINESS / GENERAL ═══
  {
    id: 'general-insurance',
    role: 'Insurance Broker',
    location: '🇺🇸 US',
    rateRange: '$2K – $4K/yr',
    rateMin: 2000,
    rateMax: 4000,
    type: 'Retainer',
    entity: ENTITIES.PERSONAL,
    crossBiz: [ENTITIES.V1, ENTITIES.V2, ENTITIES.NP],
    subpages: [],
    description: 'Umbrella liability, property, equipment, D&O coverage across all entities. Annual policy review.',
    status: STATUS.PLANNED,
    startAge: 32,
  },
];

// ───────────────────────────────────────────────────────────────
// HELPER: filter contractors for a given entity + optional subpage
// ───────────────────────────────────────────────────────────────
export function getContractorsForEntity(entityKey, subpageSlug = null) {
  return CONTRACTORS.filter(c => {
    const belongsToEntity =
      c.entity === entityKey || c.crossBiz.includes(entityKey);
    if (!belongsToEntity) return false;
    if (subpageSlug) {
      // Show if explicitly tagged for this subpage, OR if it's a cross-biz service
      return c.subpages.includes(subpageSlug) || c.crossBiz.includes(entityKey);
    }
    return true;
  });
}

// Get total estimated annual cost range for a filtered set
export function getCostRange(contractors) {
  const min = contractors.reduce((sum, c) => sum + c.rateMin, 0);
  const max = contractors.reduce((sum, c) => sum + c.rateMax, 0);
  return { min, max };
}
